services:
  - type: web
    name: enata-tarot-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: OPENAI_API_KEY
        value: "{{OPENAI_API_KEY}}"
